[View in Colaboratory](https://colab.research.google.com/github/ncfausti/jupyter_notebooks/blob/master/Lecture_Caching_Fibonacci.ipynb)

In [1]:
# This does an expensive join in Spark
def expensive_join(tables_to_join):
    results = ['This is example data']
    # Call spark etc
    return results

# We are using a dictionary as a key/value cache
cache = {}

def retrieve_or_compute(tables_to_join):
    tables_sorted = tables_to_join
    tables_sorted.sort()
    key = str(tables_sorted)
    if key in cache:
        print ('Returning from cache')
        return cache[key]
    else:
        print ('Computing the first time')
        results = expensive_join(tables_to_join)
        cache[key] = results
        return results

retrieve_or_compute(['table1','table2'])
retrieve_or_compute(['table1','table2'])

Computing the first time
Returning from cache


['This is example data']

In [2]:
import time

# This does an expensive join in Spark
def expensive_join(tables_to_join):
    results = ['This is example data']
    # Call spark etc
    return results

# We are using a dictionary as a key/value cache
cache = {}
# This tracks items' access time
accessed = {}

def get_oldest():
    oldest_age = -1
    oldest_value = ''
    for key in accessed:
        if oldest_age == -1 or accessed[key] < oldest_age:
            oldest_age = accessed[key]
            oldest_value = key
    return oldest_value

def retrieve_or_compute(tables_to_join):
    tables_sorted = tables_to_join
    tables_sorted.sort()
    key = str(tables_sorted)
    if key in cache:
        print ('Returning ', key, 'from cache')
        accessed[key] = time.time()
        return cache[key]
    else:
        print ('Computing the first time')
        results = expensive_join(tables_to_join)
        cache[key] = results
        accessed[key] = time.time()
        return results

retrieve_or_compute(['table1','table2'])
retrieve_or_compute(['table2','table3'])
retrieve_or_compute(['table3','table1'])
retrieve_or_compute(['table1','table2'])


Computing the first time
Computing the first time
Computing the first time
Returning  ['table1', 'table2'] from cache


['This is example data']

In [3]:
get_oldest()

"['table2', 'table3']"

In [4]:
accessed.pop(get_oldest())

accessed

{"['table1', 'table2']": 1522827484.9669807,
 "['table1', 'table3']": 1522827484.9662795}

In [5]:
count = 0

def recur_fibo(n):
    global count
    count = count + 1
    if n <= 1:
        return n
    else:
        return(recur_fibo(n-1) + recur_fibo(n-2))
    
print (recur_fibo(10))
print (count, 'calls')

55
177 calls


In [6]:
count = 0
cache = {}

def recur_fibo(n):
    global count
    global cache
    count = count + 1
    if n not in cache:
        if n <= 1:
            cache[n] = n
        else:
            cache[n] = (recur_fibo(n-1) + recur_fibo(n-2))
    return cache[n]
    
print (recur_fibo(10))
print (count, 'calls')

55
19 calls


In [7]:
fibo_dp = [1,1]

largest = 15
for i in range(len(fibo_dp), largest):
    fibo_dp.append(fibo_dp[i-1] + fibo_dp[i-2])
    
def fibo(i):
    global fibo_dp
    return fibo_dp[i-1]
    
print (fibo(10))

55


In [1]:
def lev(a, b):
    if not a: return len(b)
    if not b: return len(a)
    return min(lev(a[1:], b[1:])+(a[0] != b[0]), lev(a[1:], b)+1, lev(a, b[1:])+1)


a = 'robot'
b = 'bot'

print (lev(a,b))

2


In [2]:
import numpy as np

def levenshtein(s1, s2):
    if len(s1) < len(s2):
        return levenshtein(s2, s1)

    # len(s1) >= len(s2)
    if len(s2) == 0:
        return len(s1)
    
    memo = np.zeros((len(s1) +1, len(s2) + 1), np.int8)

    memo[0] = range(len(s2) + 1)
    # We are computing the *next* cell in (i+1, j+1)
    for i, c1 in enumerate(s1):
        memo[i + 1, 0] = i + 1
        for j, c2 in enumerate(s2):
            insertions = memo[i, j + 1] + 1
            deletions = memo[i + 1, j] + 1
            substitutions = memo[i, j] + (c1 != c2)
            memo[i + 1, j + 1] = min(insertions, deletions, substitutions)
            
    print (memo)
    
    return memo[-1,-1]

print (levenshtein(a,b))

[[0 1 2 3]
 [1 1 2 3]
 [2 2 1 2]
 [3 2 2 2]
 [4 3 2 3]
 [5 4 3 2]]
2
