[View in Colaboratory](https://colab.research.google.com/github/ncfausti/jupyter_notebooks/blob/master/Lecture_Matrices.ipynb)

In [0]:
import numpy as np

data = [[3.1, 3.14, 3.1415], [2.7, 2.71, 2.718]]
array1 = np.array(data)
array1

array([[ 3.1   ,  3.14  ,  3.1415],
       [ 2.7   ,  2.71  ,  2.718 ]])

In [0]:
array1.dtype

dtype('float64')

In [0]:
array1.shape

(2, 3)

## Basic Initialization

In [0]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [0]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [0]:
np.empty((5,5))

array([[  6.90194640e-310,   6.90194640e-310,   6.90194618e-310,
          6.90191466e-310,   6.90194613e-310],
       [  6.90191466e-310,   6.90194618e-310,   6.90191466e-310,
          6.90194613e-310,   6.90191469e-310],
       [  6.90194618e-310,   6.90191466e-310,   6.90194613e-310,
          6.90191466e-310,   6.90194618e-310],
       [  6.90191468e-310,   6.90194613e-310,   6.90191466e-310,
          6.90194618e-310,   6.90191469e-310],
       [  6.90194613e-310,   6.90191466e-310,   6.90194618e-310,
          6.90191466e-310,   1.02765654e-321]])

## PageRank - Matrix Multiplication

In [0]:
alpha = 0.85
beta = 1 - alpha

pr = np.array([1.0, 1.0, 1.0])
M = np.array([[0, 0, 0.5],
             [0.5, 1, 0.5],
             [0.5, 0, 0]])


for i in range(0, 15):
    pr = alpha * M @ pr + beta
    print(pr)


[ 0.575  1.85   0.575]
[ 0.394375  2.21125   0.394375]
[ 0.31760938  2.36478125  0.31760938]
[ 0.28498398  2.43003203  0.28498398]
[ 0.27111819  2.45776361  0.27111819]
[ 0.26522523  2.46954954  0.26522523]
[ 0.26272072  2.47455855  0.26272072]
[ 0.26165631  2.47668738  0.26165631]
[ 0.26120393  2.47759214  0.26120393]
[ 0.26101167  2.47797666  0.26101167]
[ 0.26092996  2.47814008  0.26092996]
[ 0.26089523  2.47820953  0.26089523]
[ 0.26088047  2.47823905  0.26088047]
[ 0.2608742  2.4782516  0.2608742]
[ 0.26087154  2.47825693  0.26087154]


In [0]:
colors = np.array(['Green', 'Blue', 'Green', 'Yellow', 'Red'])

data = np.random.randn(5,3)

In [0]:
colors

array(['Green', 'Blue', 'Green', 'Yellow', 'Red'], 
      dtype='<U6')

In [0]:
data

array([[ 3.10669249, -0.29687844,  0.52947644],
       [ 0.48135368,  0.76115606, -0.60468068],
       [ 0.48787342,  0.35323244,  0.89169349],
       [ 0.2318091 , -0.73546908, -0.2662448 ],
       [ 0.09345196,  0.92481036,  0.53960019]])

In [0]:
colors == 'Green'

array([ True, False,  True, False, False], dtype=bool)

In [0]:
data[colors=='Green']

array([[ 3.10669249, -0.29687844,  0.52947644],
       [ 0.48787342,  0.35323244,  0.89169349]])

In [0]:
arr = np.empty((8,4))

for i in range(8):
    arr[i] = i
    
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [0]:
arr[[7,2,4,1,4]]

array([[ 7.,  7.,  7.,  7.],
       [ 2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.],
       [ 1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.]])

In [0]:
arr[[-1,-5,-2]]

array([[ 7.,  7.,  7.,  7.],
       [ 3.,  3.,  3.,  3.],
       [ 6.,  6.,  6.,  6.]])

In [0]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [0]:
np.dot(arr, arr.T)

array([[   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.],
       [   0.,    4.,    8.,   12.,   16.,   20.,   24.,   28.],
       [   0.,    8.,   16.,   24.,   32.,   40.,   48.,   56.],
       [   0.,   12.,   24.,   36.,   48.,   60.,   72.,   84.],
       [   0.,   16.,   32.,   48.,   64.,   80.,   96.,  112.],
       [   0.,   20.,   40.,   60.,   80.,  100.,  120.,  140.],
       [   0.,   24.,   48.,   72.,   96.,  120.,  144.,  168.],
       [   0.,   28.,   56.,   84.,  112.,  140.,  168.,  196.]])

In [0]:
typ = ['abc']

typ == 'abc' or (type(typ) == list and typ[0] == 'abc')

True